<?php
$tmp = tempnam(sys_get_temp_dir(), 'sigma_api_'); if ($tmp === false) exit(1); unlink($tmp); putenv('SIGMAIMMO_SQLITE_PATH=' . $tmp);
require_once __DIR__ . '/../app/Database/bootstrap.php';
require_once __DIR__ . '/../app/Services/AuthService.php';
require_once __DIR__ . '/../app/Services/ApiTokenService.php';
require_once __DIR__ . '/../app/Repositories/ApiTokenRepository.php';
require_once __DIR__ . '/../app/Repositories/PropertyRepository.php';
require_once __DIR__ . '/../app/API/cAPI_Processor.php';
require_once __DIR__ . '/../app/API/PropertyAPIProcessor.php';
require_once __DIR__ . '/../app/API/PropertyAnalysisResultAPIProcessor.php';

$pdo = sigma_db(); $auth = new AuthService(); $owner = $auth->register('owner@example.test', 'password123'); $other = $auth->register('other@example.test', 'password123');
$admin = (new UserRepository($pdo))->ensureLegacyImportUser();
$tokenService = new ApiTokenService(new ApiTokenRepository($pdo)); $issued = $tokenService->issue($owner['id'], 'test');
assertApi(strlen($issued['token']) === 64, 'token is returned once with 256 bits');
assertApi($tokenService->authenticate($issued['token'])['id'] === (int)$owner['id'], 'hashed token authenticates its owner');
assertApi($tokenService->authenticate(str_repeat('0', 64)) === null, 'unknown token is rejected');
$properties = new PropertyRepository($pdo); $properties->upsert(array('id'=>'shared-one','title'=>'Shared'), $owner); $properties->upsert(array('id'=>'private-one','title'=>'Private','visibility'=>'private'), $owner);
$route = array('table'=>'properties','primary_key'=>'id','writable'=>array('id','title','visibility'));
$reader = new cAPI_Processor($pdo, $route, $other, array('id'=>'shared-one')); $read = $reader->process('GET', null); assertApi($read['data']['id'] === 'shared-one', 'shared property is visible to another authenticated user');
$hidden = false; try { (new cAPI_Processor($pdo, $route, $other, array('id'=>'private-one')))->process('GET', null); } catch (APIException $e) { $hidden = $e->status() === 404; } assertApi($hidden, 'private property is hidden from another user');
$propertyReader = new PropertyAPIProcessor($pdo, $route, $other); $propertyList = $propertyReader->process('GET', null); assertApi(count($propertyList['data']) === 1 && $propertyList['data'][0]['id'] === 'shared-one', 'property collection includes another user shared property but excludes their private property');
$propertyDetail = (new PropertyAPIProcessor($pdo, $route, $other, array('id'=>'shared-one')))->process('GET', null); assertApi($propertyDetail['data']['listing']['id'] === 'shared-one', 'property detail uses the same shared visibility scope as the collection');
$ownerProperty = new PropertyAPIProcessor($pdo, $route, $owner, array('id'=>'shared-one'));
$otherProperty = new PropertyAPIProcessor($pdo, $route, $other, array('id'=>'shared-one'));
$ownerProperty->process('PATCH', array('selection'=>'shortlist', 'notes'=>'Note du propriétaire', 'visitAt'=>'2026-08-10T14:00'));
$otherPersonal = $otherProperty->process('PATCH', array('selection'=>'a_visiter', 'notes'=>'Note privée du lecteur'));
assertApi($otherPersonal['data']['listing']['selection'] === 'a_visiter' && $otherPersonal['data']['listing']['notes'] === 'Note privée du lecteur', 'a user can classify and annotate an accessible shared property');
$ownerPersonal = $ownerProperty->process('GET', null);
assertApi($ownerPersonal['data']['listing']['selection'] === 'shortlist' && $ownerPersonal['data']['listing']['notes'] === 'Note du propriétaire', 'status and notes are isolated for each user');
assertApi($ownerPersonal['data']['listing']['visitAt'] === '2026-08-10T14:00' && !isset($otherPersonal['data']['listing']['visitAt']), 'visit information is not exposed to another user');
$invalidStatus = false; try { $otherProperty->process('PATCH', array('selection'=>'inconnu')); } catch (APIException $e) { $invalidStatus = $e->status() === 422; } assertApi($invalidStatus, 'unknown personal status is rejected');
$propertyColumns = array(); foreach ($pdo->query('PRAGMA table_info(properties)')->fetchAll() as $column) $propertyColumns[] = $column['name'];
assertApi(!in_array('selection', $propertyColumns, true) && !in_array('notes', $propertyColumns, true), 'personal columns are removed from properties');
$adminList = (new PropertyAPIProcessor($pdo, $route, $admin))->process('GET', null); assertApi(count($adminList['data']) === 2, 'admin sees shared and private properties');
$adminDetail = (new PropertyAPIProcessor($pdo, $route, $admin, array('id'=>'private-one')))->process('GET', null); assertApi($adminDetail['data']['permissions']['canManageVisibility'] === true, 'admin receives visibility management permission');
$visibilityBlocked = false; try { (new PropertyAPIProcessor($pdo, $route, $owner, array('id'=>'private-one')))->process('PATCH', array('visibility'=>'shared')); } catch (APIException $e) { $visibilityBlocked = $e->status() === 403; } assertApi($visibilityBlocked, 'non-admin owner cannot change visibility');
$published = (new PropertyAPIProcessor($pdo, $route, $admin, array('id'=>'private-one')))->process('PATCH', array('visibility'=>'shared')); assertApi($published['data']['listing']['visibility'] === 'shared', 'admin can publish any property');
$now = gmdate('c'); $analysisInsert = $pdo->prepare("INSERT INTO analyses (property_id,type,status,summary_json,result_json,created_at,updated_at) VALUES (:property_id,'locatif','completed',:summary_json,:result_json,:now,:now)"); $analysisInsert->execute(array(':property_id'=>'shared-one', ':summary_json'=>'{"score":null}', ':result_json'=>'{"score":82,"note_globale":{"score":71},"annonce":{"revenus":{"total_annonce_an":18800}},"exec_summary":{"rendement_net_min_pct":6.1,"cashflow_min_mois":279}}', ':now'=>$now));
$propertyList = $propertyReader->process('GET', null); $galleryAnalysis = $propertyList['data'][0]['analyses']['locatif'];
assertApi($galleryAnalysis['score'] === 71.0, 'property collection rebuilds a missing gallery score from the stored analysis');
assertApi($galleryAnalysis['revenuBrutAnnuel'] === 18800.0 && $galleryAnalysis['rendementNetPct'] === 6.1 && $galleryAnalysis['cashflowMensuel'] === 279.0, 'property collection rebuilds missing rental figures from the stored analysis');
$priceInsert = $pdo->prepare("INSERT INTO analyses (property_id,type,status,result_json,created_at,updated_at) VALUES (:property_id,'prix','completed',:result_json,:now,:now)"); $priceInsert->execute(array(':property_id'=>'shared-one', ':result_json'=>'{"api_data":{"dvf_rows":[{"large":"payload"}]}}', ':now'=>$now));
$propertyList = $propertyReader->process('GET', null);
assertApi(!array_key_exists('prix', $propertyList['data'][0]['analyses']), 'property collection excludes the large raw market-price analysis');
$analysisRoute = array('table'=>'analyses','primary_key'=>'id','writable'=>array());
$sharedAnalysis = (new PropertyAnalysisResultAPIProcessor($pdo, $analysisRoute, $other, array('property_id'=>'shared-one','type'=>'locatif')))->process('GET', null); assertApi($sharedAnalysis['data']['analysis']['score'] === 82, 'analysis result of a shared property is visible to another authenticated user');
$analysisDeleteBlocked = false; try { (new PropertyAnalysisResultAPIProcessor($pdo, $analysisRoute, $other, array('property_id'=>'shared-one','type'=>'locatif')))->process('DELETE', null); } catch (APIException $e) { $analysisDeleteBlocked = $e->status() === 404; } assertApi($analysisDeleteBlocked, 'analysis result of a shared property remains deletable only by its owner');
$blocked = false; try { (new cAPI_Processor($pdo, $route, $other, array('id'=>'shared-one')))->process('PATCH', array('title'=>'stolen')); } catch (APIException $e) { $blocked = $e->status() === 403; } assertApi($blocked, 'shared property remains writable only by its owner');
$created = (new cAPI_Processor($pdo, $route, $other))->process('POST', array('id'=>'other-one','title'=>'Other','visibility'=>'private')); assertApi($created['data']['user_id'] === (int)$other['id'], 'generic create assigns ownership');
$routes = json_decode(file_get_contents(__DIR__ . '/../public/api/routes_wl.json'), true); assertApi(is_array($routes) && count($routes['routes']) >= 6, 'route whitelist declares API v1 resources');
$htaccess = file_get_contents(__DIR__ . '/../public/.htaccess'); assertApi(strpos($htaccess, '(?!index\\.php$)') !== false, 'Apache legacy endpoint rule excludes the API v1 front controller');
unlink($tmp); echo "api_v1_test ok\n";
function assertApi($condition, $message) { if (!$condition) { fwrite(STDERR, 'Assertion failed: ' . $message . "\n"); exit(1); } }
